#!/usr/bin/env sh
#-*-mode: Shell-script; coding: utf-8;-*-
script=$(basename $0)
dir=$(cd $(dirname $0); pwd)
iam=${dir}/${script}
gccgo=yes # if anything else, will not use gccgo even if present

PATH=${PATH}:${dir}
task=$script
name=$1
name=${name:=unknown}

gitfile=git.go
echo "$(scripts/git.sh)" > ${gitfile}

type go > /dev/null 2>&1
if [[ $? == 0 ]]; then
  compy= # use gccgo to compile if its present, cause faster runtime
  type gccgo > /dev/null 2>&1
  [[ $gccgo != 'yes' && $? == 0 ]] && compy='--compiler=gccgo'

  cd ${dir}
  args=""
  if [[ $task == 'build' ]]; then
    args="-o ${name} ${gitfile} $(ls -d *.go | grep -v ${gitfile})"
  elif [[ $task == 'test' ]]; then
    args="$(find . -name '*_test.go' -type f)"
  fi
  go ${task} ${compy} ${args}
  exit $?
fi

echo "no go executable found to build anything with, fix it then rerun"
exit 1
